@echo off
echo Cleaning old build...
if exist dist rmdir /s /q dist
echo Building frontend...
call npx vite build
echo Building backend without vite...
call npx esbuild server/index.ts --platform=node --bundle --format=esm --outdir=dist --packages=external
echo Starting server...
call node dist/index.js
