@echo off
echo Deleting old build...
rmdir /s /q dist 2>nul

echo Building frontend...
call npx vite build

echo Building backend...
call npx esbuild server/production.ts --platform=node --bundle --format=esm --outdir=dist --packages=external

echo Starting server...
call node dist/production.js
