-- Price Update Summary
-- Total updates: 222
-- Generated on: 2025-07-29T16:26:25.224Z

UPDATE products SET price = '1026' WHERE LOWER(name) = 'amouage – honor man';
UPDATE products SET price = '1026' WHERE LOWER(name) = 'amouage – interlude woman';
UPDATE products SET price = '446' WHERE LOWER(name) = 'armani - si passione';
UPDATE products SET price = '446' WHERE LOWER(name) = 'armani - si (black)';
UPDATE products SET price = '432' WHERE LOWER(name) = 'armani - my way';
UPDATE products SET price = '359' WHERE LOWER(name) = 'armani - stronger with you';
UPDATE products SET price = '362' WHERE LOWER(name) = 'armani - stronger with you intensely';
UPDATE products SET price = '362' WHERE LOWER(name) = 'armani - stronger with you absolutely';
UPDATE products SET price = '322' WHERE LOWER(name) = 'armani - acqua di gio';
UPDATE products SET price = '527' WHERE LOWER(name) = 'armani – code';
UPDATE products SET price = '382' WHERE LOWER(name) = 'azzaro - wanted by night';
UPDATE products SET price = '351' WHERE LOWER(name) = 'boss - bottled night';
UPDATE products SET price = '226' WHERE LOWER(name) = 'boss – just different';
UPDATE products SET price = '1135' WHERE LOWER(name) = 'bottega veneta - ix violetta';
UPDATE products SET price = '1138' WHERE LOWER(name) = 'bottega veneta - v lauro';
UPDATE products SET price = '1129' WHERE LOWER(name) = 'bottega veneta - xv salvia blu';
UPDATE products SET price = '1134' WHERE LOWER(name) = 'bottega veneta - vii lilla';
UPDATE products SET price = '392' WHERE LOWER(name) = 'burberry - weekend';
UPDATE products SET price = '489' WHERE LOWER(name) = 'burberry - my';
UPDATE products SET price = '365' WHERE LOWER(name) = 'burberry – hero';
UPDATE products SET price = '405' WHERE LOWER(name) = 'burberry – her london dream';
UPDATE products SET price = '489' WHERE LOWER(name) = 'burberry – goddess';
UPDATE products SET price = '400' WHERE LOWER(name) = 'bvlgari – man in black';
UPDATE products SET price = '475' WHERE LOWER(name) = 'bvlgari – wood essence';
UPDATE products SET price = '467' WHERE LOWER(name) = 'bvlgari – blv pour homme';
UPDATE products SET price = '454' WHERE LOWER(name) = 'bvlgari – omnia crystalline';
UPDATE products SET price = '783' WHERE LOWER(name) = 'byredo - marijuana';
UPDATE products SET price = '1080' WHERE LOWER(name) = 'byredo - vanille antique';
UPDATE products SET price = '864' WHERE LOWER(name) = 'byredo - super cedar';
UPDATE products SET price = '729' WHERE LOWER(name) = 'byredo - black saffron';
UPDATE products SET price = '783' WHERE LOWER(name) = 'byredo - blanche';
UPDATE products SET price = '397' WHERE LOWER(name) = 'calvin klein – euphoria';
UPDATE products SET price = '459' WHERE LOWER(name) = 'carolina herrera - very good girl';
UPDATE products SET price = '405' WHERE LOWER(name) = 'carolina herrera - good girl';
UPDATE products SET price = '270' WHERE LOWER(name) = 'carolina herrera – 212 vip black';
UPDATE products SET price = '475' WHERE LOWER(name) = 'chanel - n5';
UPDATE products SET price = '540' WHERE LOWER(name) = 'chanel - bleu de chanel';
UPDATE products SET price = '581' WHERE LOWER(name) = 'chanel – allure homme sport';
UPDATE products SET price = '367' WHERE LOWER(name) = 'chanel – allure homme';
UPDATE products SET price = '513' WHERE LOWER(name) = 'chanel – coco eau de parfum';
UPDATE products SET price = '527' WHERE LOWER(name) = 'chanel – allure sensuelle';
UPDATE products SET price = '513' WHERE LOWER(name) = 'chanel – cristalle';
UPDATE products SET price = '500' WHERE LOWER(name) = 'chanel – gabrielle';
UPDATE products SET price = '527' WHERE LOWER(name) = 'chanel – chance eau de parfum';
UPDATE products SET price = '527' WHERE LOWER(name) = 'chanel – chance eau fraiche';
UPDATE products SET price = '527' WHERE LOWER(name) = 'chanel – chance eau tendre';
UPDATE products SET price = '1377' WHERE LOWER(name) = 'creed - aventus';
UPDATE products SET price = '1377' WHERE LOWER(name) = 'creed - viking';
UPDATE products SET price = '1242' WHERE LOWER(name) = 'creed – wind flowers';
UPDATE products SET price = '1242' WHERE LOWER(name) = 'creed - queen of silk';
UPDATE products SET price = '270' WHERE LOWER(name) = 'davidoff - cool water';
UPDATE products SET price = '540' WHERE LOWER(name) = 'dior - sauvage elixir';
UPDATE products SET price = '486' WHERE LOWER(name) = 'dior - miss dior';
UPDATE products SET price = '486' WHERE LOWER(name) = 'dior – miss dior blooming bouquet';
UPDATE products SET price = '500' WHERE LOWER(name) = 'dior - jadore';
UPDATE products SET price = '446' WHERE LOWER(name) = 'dior - sauvage';
UPDATE products SET price = '405' WHERE LOWER(name) = 'dior - fahrenheit';
UPDATE products SET price = '378' WHERE LOWER(name) = 'dior – homme intense';
UPDATE products SET price = '405' WHERE LOWER(name) = 'dior – addict eau fraiche';
UPDATE products SET price = '405' WHERE LOWER(name) = 'dior – addict eau de parfum';
UPDATE products SET price = '413' WHERE LOWER(name) = 'dior – joy intense';
UPDATE products SET price = '432' WHERE LOWER(name) = 'dior – joy';
UPDATE products SET price = '338' WHERE LOWER(name) = 'dolce&gabbana - k';
UPDATE products SET price = '338' WHERE LOWER(name) = 'dolce&gabbana – q';
UPDATE products SET price = '297' WHERE LOWER(name) = 'dolce&gabbana – light blue';
UPDATE products SET price = '405' WHERE LOWER(name) = 'dolce&gabbana – the only one 2';
UPDATE products SET price = '459' WHERE LOWER(name) = 'dolce&gabbana – the one';
UPDATE products SET price = '435' WHERE LOWER(name) = 'dolce&gabbana – the only one';
UPDATE products SET price = '374' WHERE LOWER(name) = 'givenchy - gentleman';
UPDATE products SET price = '405' WHERE LOWER(name) = 'givenchy - society';
UPDATE products SET price = '410' WHERE LOWER(name) = 'givenchy – l’interdit eau de parfum rouge';
UPDATE products SET price = '454' WHERE LOWER(name) = 'gucci – bloom';
UPDATE products SET price = '489' WHERE LOWER(name) = 'gucci – flora gorgeous orchid';
UPDATE products SET price = '489' WHERE LOWER(name) = 'gucci – flora gorgeous jasmine';
UPDATE products SET price = '489' WHERE LOWER(name) = 'gucci – flora gorgeous gardenia';
UPDATE products SET price = '473' WHERE LOWER(name) = 'hermes – merveilles';
UPDATE products SET price = '987' WHERE LOWER(name) = 'initio - side effect';
UPDATE products SET price = '945' WHERE LOWER(name) = 'initio - musk therapy';
UPDATE products SET price = '988' WHERE LOWER(name) = 'initio - oud for happiness';
UPDATE products SET price = '484' WHERE LOWER(name) = 'jean paul gaultier - le male elixir';
UPDATE products SET price = '477' WHERE LOWER(name) = 'jean paul gaultier - la belle';
UPDATE products SET price = '467' WHERE LOWER(name) = 'jean paul gaultier - divine';
UPDATE products SET price = '445' WHERE LOWER(name) = 'jean paul gaultier - le beau le parfum';
UPDATE products SET price = '394' WHERE LOWER(name) = 'jean paul gaultier - le beau';
UPDATE products SET price = '442' WHERE LOWER(name) = 'jean paul gaultier - le male le parfum';
UPDATE products SET price = '414' WHERE LOWER(name) = 'jean paul gaultier - le male';
UPDATE products SET price = '382' WHERE LOWER(name) = 'jean paul gaultier - scandal';
UPDATE products SET price = '382' WHERE LOWER(name) = 'jean paul gaultier - scandal pour homme';
UPDATE products SET price = '399' WHERE LOWER(name) = 'jpg - scandal gold';
UPDATE products SET price = '933' WHERE LOWER(name) = 'killian - angels'' share';
UPDATE products SET price = '918' WHERE LOWER(name) = 'killian - roses on ice';
UPDATE products SET price = '934' WHERE LOWER(name) = 'kilian - black phantom';
UPDATE products SET price = '990' WHERE LOWER(name) = 'kilian - good girl gone bad';
UPDATE products SET price = '1050' WHERE LOWER(name) = 'kilian - good girl gone bad extreme';
UPDATE products SET price = '977' WHERE LOWER(name) = 'kilian - rolling in love';
UPDATE products SET price = '755' WHERE LOWER(name) = 'kilian – bad boys are no good but good boys are no fun';
UPDATE products SET price = '405' WHERE LOWER(name) = 'lancome – idole';
UPDATE products SET price = '459' WHERE LOWER(name) = 'lancome – magie noire';
UPDATE products SET price = '446' WHERE LOWER(name) = 'lancome – climat';
UPDATE products SET price = '745' WHERE LOWER(name) = 'le labo – santal 33';
UPDATE products SET price = '1161' WHERE LOWER(name) = 'louis vuitton - attrape-reves';
UPDATE products SET price = '1107' WHERE LOWER(name) = 'louis vuitton - apogee';
UPDATE products SET price = '1188' WHERE LOWER(name) = 'louis vuitton - cactus garden';
UPDATE products SET price = '1094' WHERE LOWER(name) = 'louis vuitton - orage';
UPDATE products SET price = '1431' WHERE LOWER(name) = 'louis vuitton - ombre nomade';
UPDATE products SET price = '1323' WHERE LOWER(name) = 'louis vuitton - matiere noire';
UPDATE products SET price = '702' WHERE LOWER(name) = 'maison francis kurkdjian - grand soir';
UPDATE products SET price = '689' WHERE LOWER(name) = 'maison francis kurkdjian - 724';
UPDATE products SET price = '783' WHERE LOWER(name) = 'maison francis kurkdjian - baccarat rouge 540 eau de parfum';
UPDATE products SET price = '999' WHERE LOWER(name) = 'maison francis kurkdjian -baccarat rouge 540 extrait de parfum';
UPDATE products SET price = '756' WHERE LOWER(name) = 'maison francis kurkdjian - oud satin mood';
UPDATE products SET price = '528' WHERE LOWER(name) = 'maison margiela - beach walk';
UPDATE products SET price = '528' WHERE LOWER(name) = 'maison margiela – when the rain stops';
UPDATE products SET price = '528' WHERE LOWER(name) = 'maison margiela – coffee break';
UPDATE products SET price = '528' WHERE LOWER(name) = 'maison margiela – under the lemon trees';
UPDATE products SET price = '528' WHERE LOWER(name) = 'maison margiela - jazz club';
UPDATE products SET price = '810' WHERE LOWER(name) = 'marc antoine barrois - encelade';
UPDATE products SET price = '810' WHERE LOWER(name) = 'marc antonio barrois - ganymede';
UPDATE products SET price = '810' WHERE LOWER(name) = 'marc antoine barrois – tilia';
UPDATE products SET price = '352' WHERE LOWER(name) = 'marc jacobs – daisy';
UPDATE products SET price = '402' WHERE LOWER(name) = 'marc jacobs – decadence rouge noir edition';
UPDATE products SET price = '394' WHERE LOWER(name) = 'marc jacobs – decadence';
UPDATE products SET price = '520' WHERE LOWER(name) = 'mancera - red tobacco';
UPDATE products SET price = '520' WHERE LOWER(name) = 'mancera – coco vanille';
UPDATE products SET price = '520' WHERE LOWER(name) = 'mancera – vanille exclusive';
UPDATE products SET price = '520' WHERE LOWER(name) = 'mancera – tonka cola';
UPDATE products SET price = '810' WHERE LOWER(name) = 'memo – italian leather';
UPDATE products SET price = '810' WHERE LOWER(name) = 'memo - russian leather';
UPDATE products SET price = '409' WHERE LOWER(name) = 'molecula - 02';
UPDATE products SET price = '409' WHERE LOWER(name) = 'molecule – 04';
UPDATE products SET price = '409' WHERE LOWER(name) = 'molecule – 05';
UPDATE products SET price = '378' WHERE LOWER(name) = 'montblanc – legend';
UPDATE products SET price = '378' WHERE LOWER(name) = 'montblanc – legend red';
UPDATE products SET price = '378' WHERE LOWER(name) = 'moschino - toy bubblegum';
UPDATE products SET price = '378' WHERE LOWER(name) = 'moschino - toy 2';
UPDATE products SET price = '378' WHERE LOWER(name) = 'moschino - toy boy';
UPDATE products SET price = '459' WHERE LOWER(name) = 'mugler – aura';
UPDATE products SET price = '405' WHERE LOWER(name) = 'mugler - angel';
UPDATE products SET price = '405' WHERE LOWER(name) = 'mugler - nova';
UPDATE products SET price = '510' WHERE LOWER(name) = 'narciso rodriguez - for her eau de parfum';
UPDATE products SET price = '490' WHERE LOWER(name) = 'narciso rodriguez - poudree';
UPDATE products SET price = '470' WHERE LOWER(name) = 'narciso rodriguez - rouge';
UPDATE products SET price = '510' WHERE LOWER(name) = 'narciso rodriguez - for her eau de parfum';
UPDATE products SET price = '550' WHERE LOWER(name) = 'nassomato - black afgano';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - viride';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - boccanera';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - bergamask';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - brutus';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - seminalis';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - coium';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - stercus';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - terroni';
UPDATE products SET price = '645' WHERE LOWER(name) = 'orto parisi - megamare';
UPDATE products SET price = '420' WHERE LOWER(name) = 'paco rabanne - fame';
UPDATE products SET price = '410' WHERE LOWER(name) = 'paco rabanne - 1 milion';
UPDATE products SET price = '410' WHERE LOWER(name) = 'paco rabanne - phantom';
UPDATE products SET price = '450' WHERE LOWER(name) = 'paco rabanne – 1 million parfum';
UPDATE products SET price = '376' WHERE LOWER(name) = 'paco rabanne – pure xs';
UPDATE products SET price = '382' WHERE LOWER(name) = 'paco rabanne – pure xs for her';
UPDATE products SET price = '370' WHERE LOWER(name) = 'paco rabanne – invictus';
UPDATE products SET price = '404' WHERE LOWER(name) = 'paco rabanne – olympea';
UPDATE products SET price = '710' WHERE LOWER(name) = 'parfums de marly - delina';
UPDATE products SET price = '810' WHERE LOWER(name) = 'parfums de marly - layton';
UPDATE products SET price = '810' WHERE LOWER(name) = 'parfums de marly - pegasus';
UPDATE products SET price = '432' WHERE LOWER(name) = 'prada - black';
UPDATE products SET price = '500' WHERE LOWER(name) = 'prada – paradoxe intense';
UPDATE products SET price = '1140' WHERE LOWER(name) = 'roja – danger pour homme';
UPDATE products SET price = '1140' WHERE LOWER(name) = 'roja – ahlam';
UPDATE products SET price = '544' WHERE LOWER(name) = 'sospiro – erba pura';
UPDATE products SET price = '534' WHERE LOWER(name) = 'sospiro – opera';
UPDATE products SET price = '890' WHERE LOWER(name) = 'tiziana terenzi - andromeda';
UPDATE products SET price = '865' WHERE LOWER(name) = 'tiziana terenzi - kirke';
UPDATE products SET price = '1093' WHERE LOWER(name) = 'tom ford - costa azzurra';
UPDATE products SET price = '1112' WHERE LOWER(name) = 'tom ford - vanille fatale';
UPDATE products SET price = '1105' WHERE LOWER(name) = 'tom ford - soleil brulant';
UPDATE products SET price = '1108' WHERE LOWER(name) = 'tom ford - rose prick';
UPDATE products SET price = '1109' WHERE LOWER(name) = 'tom ford - santal blush';
UPDATE products SET price = '648' WHERE LOWER(name) = 'tom ford - noir';
UPDATE products SET price = '756' WHERE LOWER(name) = 'tom ford - noir extreme';
UPDATE products SET price = '702' WHERE LOWER(name) = 'tom ford - black orchid';
UPDATE products SET price = '402' WHERE LOWER(name) = 'tom ford - vanilla s*x';
UPDATE products SET price = '1105' WHERE LOWER(name) = 'tom ford - bitter peach';
UPDATE products SET price = '1105' WHERE LOWER(name) = 'tom ford - lost cherry';
UPDATE products SET price = '1105' WHERE LOWER(name) = 'tom ford - tobacco vanille';
UPDATE products SET price = '1105' WHERE LOWER(name) = 'tom ford - oud wood';
UPDATE products SET price = '1105' WHERE LOWER(name) = 'tom ford - f*cking fabulous';
UPDATE products SET price = '810' WHERE LOWER(name) = 'tom ford - ombre leather';
UPDATE products SET price = '579' WHERE LOWER(name) = 'trussardi - behind the curtain';
UPDATE products SET price = '579' WHERE LOWER(name) = 'trussardi - fiori chiari';
UPDATE products SET price = '579' WHERE LOWER(name) = 'trussardi - musc noir';
UPDATE products SET price = '579' WHERE LOWER(name) = 'trussardi - passegiata in galleria';
UPDATE products SET price = '579' WHERE LOWER(name) = 'trussardi - limitless shopping';
UPDATE products SET price = '444' WHERE LOWER(name) = 'trussardi – donna';
UPDATE products SET price = '459' WHERE LOWER(name) = 'valentino - born in roma yellow dream';
UPDATE products SET price = '443' WHERE LOWER(name) = 'valentino - donna coral fantasy';
UPDATE products SET price = '423' WHERE LOWER(name) = 'valentino - pink pp';
UPDATE products SET price = '334' WHERE LOWER(name) = 'versace - eros';
UPDATE products SET price = '334' WHERE LOWER(name) = 'versace – eros flame';
UPDATE products SET price = '364' WHERE LOWER(name) = 'versace – crystal noir';
UPDATE products SET price = '364' WHERE LOWER(name) = 'versace – bright crystal';
UPDATE products SET price = '364' WHERE LOWER(name) = 'versace – bright crystal absolu';
UPDATE products SET price = '374' WHERE LOWER(name) = 'versace – dylan blue femme';
UPDATE products SET price = '376' WHERE LOWER(name) = 'versace – pour femme dylan purple';
UPDATE products SET price = '382' WHERE LOWER(name) = 'viktor rolf - spicebomb (extreme)';
UPDATE products SET price = '720' WHERE LOWER(name) = 'xerjoff - 1861 naxos';
UPDATE products SET price = '720' WHERE LOWER(name) = 'xerjoff - more than words';
UPDATE products SET price = '720' WHERE LOWER(name) = 'xerjoff - oud stars luxor';
UPDATE products SET price = '720' WHERE LOWER(name) = 'xerjoff - erba pura';
UPDATE products SET price = '720' WHERE LOWER(name) = 'xerjoff - accento';
UPDATE products SET price = '720' WHERE LOWER(name) = 'xerjoff – opera';
UPDATE products SET price = '484' WHERE LOWER(name) = 'yves saint laurent - black opium';
UPDATE products SET price = '484' WHERE LOWER(name) = 'yves saint laurent - black opium (intense)';
UPDATE products SET price = '484' WHERE LOWER(name) = 'yves saint laurent - black opium (extreme)';
UPDATE products SET price = '505' WHERE LOWER(name) = 'yves saint laurent - libre';
UPDATE products SET price = '530' WHERE LOWER(name) = 'yves saint laurent – libre intense';
UPDATE products SET price = '450' WHERE LOWER(name) = 'yves saint laurent - y';
UPDATE products SET price = '390' WHERE LOWER(name) = 'yves saint laurent – la nuit de l’homme';
UPDATE products SET price = '354' WHERE LOWER(name) = 'zadig & voltaire – this is him';
UPDATE products SET price = '354' WHERE LOWER(name) = 'zadig & voltaire – this is her';
UPDATE products SET price = '368' WHERE LOWER(name) = 'zadig & voltaire – this is her! undressed';
UPDATE products SET price = '372' WHERE LOWER(name) = 'zadig & voltaire – this is him! vibes of freedom';
UPDATE products SET price = '362' WHERE LOWER(name) = 'zadig & voltaire – this is us!';